### PR TITLE
73 uploads should respect the do not scan this and scan only this settings

### LINKED ISSUE #73: Uploads should respect the `Do not scan this` and `Scan only this` settings
Uploads should respect the `Do not scan this` and `Scan only this` settings.

**Administrators should be made aware by a small explanatory text that by using the** `Do not scan this` **and** `Scan only this` **settings, users with malicious intentions can upload and also distribute infected files in the Nextcloud environment.**

## Steps to reproduce
- Use either the  `Do not scan this` or `Scan only this` settings to have a folder which contents should not be scanned.
- Upload a file to this folder
- The file will still be scanned if Vaas is correctly set and activated

## Expected
The files that would be affected by the blocklist or allowlist should behave accordingly and not be scanned if they are to be uploaded to the corresponding paths. For example: The folder `Unscanned/` should not be scanned. If a file is uploaded to this folder, it should not be scanned according to the rule.

## Actual
A file that is uploaded directly to a folder that should not actually be scanned due to the blocklist is scanned after all.

### PR DESCRIPTION
**Pull request by lennartdohmann**
Closes #73

### CODE REVIEW

**Comment by unglaublicherdude** [comment]
I would prefer also changing the names of the two lists in the code, because I am also always confused about the meaning, when reading the code.

File: lib/Service/VerdictService.php [hunk 1]
```diff
@@ -255,4 +248,27 @@ private function createAndConnectVaas(): Vaas {
...
+    /**
+     * Checks if the file is in the blocklist or not in the allowlist and throws an exception if it is not allowed to scan the file.
+     * @param string $filePath
+     * @return bool
+     */
+    public function isAllowedByAllowAndBlocklist(string $filePath): bool {
+        $blocklist = $this->getBlocklist();
+        $this->logger->debug("Blocklist: " . implode(", ", $blocklist));
+        foreach ($blocklist as $blocklistItem) {
+            if (str_contains(strtolower($filePath), strtolower($blocklistItem))) {
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:261]: What pattern are we intended to use in this field? all substrings, prefixes (for pathes)?

mypath for example will match on

/mypath/file.php but also on
/path/mypath.php

File: templates/admin.php
Comment (unglaublicherdude) [inline templates/admin.php:1]: The 'Scan only this' setting should also give a hint, that the 'Do not scan this' setting will basically overwrite it.

So with having mypath in both settings, VaaS won't actually scan anything.

File: lib/Service/VerdictService.php [hunk 2]
```diff
@@ -255,4 +248,27 @@ private function createAndConnectVaas(): Vaas {
...
 		return $vaas;
 	}
+
+    /**
+     * Checks if the file is in the blocklist or not in the allowlist and throws an exception if it is not allowed to scan the file.
+     * @param string $filePath
+     * @return bool
+     */
+    public function isAllowedByAllowAndBlocklist(string $filePath): bool {
+        $blocklist = $this->getBlocklist();
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:258]:
```suggestion
        $neverScanSubstrings = $this->getNeverScanSubstrings();
```

File: lib/Service/VerdictService.php [hunk 3]
```diff
@@ -255,4 +248,27 @@ private function createAndConnectVaas(): Vaas {
...
+        $this->logger->debug("Blocklist: " . implode(", ", $blocklist));
+        foreach ($blocklist as $blocklistItem) {
+            if (str_contains(strtolower($filePath), strtolower($blocklistItem))) {
+                return false;
+            }
+        }
+        $allowlist = $this->getAllowlist();
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:265]:
```suggestion
        $onlyScanSubstrings = $this->getOnlyScanSubstrings();
```

**Comment by unglaublicherdude** [comment]
Also. Please add some Unittests for the `isAllowedByAllowAndBlocklist` function.

File: templates/admin.php [hunk 4]
```diff
@@ -64,6 +64,9 @@
         </table>
         <input class="submit-button" id="auth_submit" type="submit" value="<?php p($l->t('Save'));?>" />
         <span id="auth_save_msg"></span>
+        <div class="warning">
+            <strong>Caution:</strong> The use of the <em>"Scan only this"</em> and <em>"Do not scan this"</em> settings should be approached with caution. Using these settings allows malicious users to upload and distribute malicious content via the Nextcloud instance. It is recommended that you carefully consider the implications of these settings and use them in a way that does not jeopardize the security of your system and data.
```
Comment (unglaublicherdude) [inline templates/admin.php:68]: The sentence "Using these settings allows malicious users to upload and distribute malicious content via the Nextcloud instance." feels a bit off, because this is also possible without any antivirus running in Nextcloud, but this sentence suggests that the settings will open this security risk.

Comment (unglaublicherdude) [reply templates/admin.php:68]: I also would recommend here to add examples, what mistakes can be made by using the settings

**Review by unglaublicherdude — CHANGES_REQUESTED** [review]

**Review by doxthree — APPROVED** [review]

File: lib/AvirWrapper.php [hunk 5]
```diff
@@ -126,7 +126,11 @@ function () use ($path, $logger) {
 					$localPath = $this->getLocalFile($path);
 					$filesize = $this->filesize($path);
 					$logger->debug("Closing " . $localPath . " with size " . $filesize);
-
+                    
+                    if (!$this->verdictService->isAllowedByAllowAndBlocklist($localPath)) {
```
Comment (unglaublicherdude) [inline lib/AvirWrapper.php:130]:
```suggestion
                    if (!$this->verdictService->shouldWeScan($localPath)) {
```

File: lib/Service/VerdictService.php [hunk 6]
```diff
@@ -56,21 +55,20 @@ public function __construct(LoggerInterface $logger, IAppConfig $appConfig, File
...
-	 * Scans a file for malicious content with G DATA Verdict-as-a-Service and handles the result.
-	 * @param int $fileId
-	 * @return VaasVerdict
-	 * @throws InvalidPathException
-	 * @throws InvalidSha256Exception
-	 * @throws NotFoundException
-	 * @throws UploadFailedException
-	 * @throws TimeoutException
-	 * @throws NotPermittedException
-	 * @throws FileDoesNotExistException if the VaaS SDK could not find the file
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:69]: Why remove the description?

Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:69]: Why remove the descriptions?

File: lib/Service/VerdictService.php [hunk 7]
```diff
@@ -79,23 +77,9 @@ public function scanFileById(int $fileId): VaasVerdict {
...
-		$allowlist = $this->getAllowlist();
-		$this->logger->debug("Allowlist: " . implode(", ", $allowlist));
-		foreach ($allowlist as $allowlistItem) {
-			if (!str_contains(strtolower($filePath), strtolower($allowlistItem))) {
-				$this->logger->debug("File " . $node->getName() . " (" . $fileId . ") is not in the allowlist and will not be scanned.");
-				throw new NotPermittedException("File is not in the allowlist");
-			}
-		}
+        if (!$this->isAllowedByAllowAndBlocklist($filePath)) {
+            throw new NotPermittedException("File is not allowed to be scanned by the allowlist/blocklist");
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:81]:
```suggestion
            throw new NotPermittedException("File is not allowed to be scanned by the 'Only Scan this' and 'Do not scan this' settings ");
```

**Comment by unglaublicherdude** [comment]
Is there a reason why the 'Scan only this' and 'Never scan this' settings are comma seperated lists?
I have seen an getValueArray function on the IAppConfig interface. Couldn't we use that for those lists?

**Review by pstadermann — CHANGES_REQUESTED** [review]

File: lib/Service/VerdictService.php [hunk 8]
```diff
@@ -252,4 +245,27 @@ private function createAndConnectVaas(): Vaas {
...
+		$blocklist = $this->getBlocklist();
+		$this->logger->debug("Blocklist: " . implode(", ", $blocklist));
+		foreach ($blocklist as $blocklistItem) {
+			if (str_contains(strtolower($filePath), strtolower($blocklistItem))) {
+				return false;
+			}
+		}
+		$allowlist = $this->getAllowlist();
+		$this->logger->debug("Allowlist: " . implode(", ", $allowlist));
+		foreach ($allowlist as $allowlistItem) {
```
Comment (Phorkyas) [inline lib/Service/VerdictService.php:264]: Maybe I just don't get it, or the semantic is intended like that,... but doesn't the code here mean that a filename has to match _all_ entries in the allow list, instead of one? Say I want to allow you to scan only "eicar.txt" and "eicar.com" and I put both into the allow list. Then as a result neither would be scanned, because a file cannot match both.
(In this case I could make one entry "eicar." as a kind of wildcard, but the behavior would be very surprsing to me..)

File: lib/Service/VerdictService.php [hunk 9]
```diff
@@ -193,6 +182,10 @@ public function tagLastScannedFile(string $localPath, int $fileId): void {
 			$this->tagFile($fileId, TagService::WONT_SCAN);
 			return;
 		}
+		if (!$this->isAllowedByAllowAndBlocklist($localPath)) {
+			$this->tagFile($fileId, TagService::UNSCANNED);
```
Comment (Phorkyas) [inline lib/Service/VerdictService.php:186]: Not too familiar with the tagging semantics. Only a feeling that `TagService::WONT_SCAN` could be more suited, because you kind of handled the file, but are not allowed to say a verdict. Just imagine a user hitting the "Scan"-Button multiple times, but the "Unscanned" tag never changes. But maybe it's fine, dunno.

Comment (Phorkyas) [reply lib/Service/VerdictService.php:186]: Strange, there were comments already on this, but I don't see them here. So maybe just delete these, here.

**Comment by unglaublicherdude** [comment]
@lennartdohmann you still work on this? because the naming and wording recommendations are not tackled yet as far as I can see.

**Comment by lennartdohmann** [comment]
@unglaublicherdude I merged the #88 into this. Can you give me a thumbs up if you agree to merge this now?

**Review by unglaublicherdude — APPROVED** [review]
