### PR TITLE
Fix for #62

### LINKED ISSUE #62: Bug: Empty files are marked as over 256MB
If the file size is zero, then PHP evaluates this zero as "false" and this expression becomes "true", which leads to a file size that is too large for empty files.

https://github.com/GDATASoftwareAG/nextcloud-gdata-antivirus/blob/49b9f62d701be7dc747a898d56f4ce576e606c24/lib/Service/VerdictService.php#L144

### PR DESCRIPTION
**Pull request by lennartdohmann**
Closes #62 
Fix if the file size is zero, the app evaluates the file as too large to scan

### CODE REVIEW

**Comment by unglaublicherdude** [comment]
This could be a good unit-test for this function.

File: lib/Service/VerdictService.php [hunk 1]
```diff
@@ -141,6 +141,7 @@ private function tagFile(int $fileId, string $tagName) {
 	 */
     public static function isFileTooLargeToScan(string $path): bool {
         $size = filesize($path);
+        if ($size === 0) { return false; }
         return !$size || $size > self::MAX_FILE_SIZE;
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:145]: The problem would be still present for a null-value in the size.

```php
<?php

$foobar = null;
echo var_export(!$foobar); // true

$foobar = 0;
echo var_export(!$foobar); // true
```

Comment (lennartdohmann) [reply lib/Service/VerdictService.php:145]: The functions has PHPDocs that tell us it can only return an integer or "false" on any failure.

File: lib/Service/VerdictService.php [hunk 2]
```diff
@@ -141,6 +141,7 @@ private function tagFile(int $fileId, string $tagName) {
 	 */
     public static function isFileTooLargeToScan(string $path): bool {
         $size = filesize($path);
+        if ($size === 0) { return false; }
```
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:144]:
```suggestion
        if (!$size) { return false; }
```

File: lib/Service/VerdictService.php (hunk 1 above)
Comment (unglaublicherdude) [inline lib/Service/VerdictService.php:145]:
```suggestion
        return $size > self::MAX_FILE_SIZE;
```

Comment (lennartdohmann) [reply lib/Service/VerdictService.php:145]: Since the function can return a boolean false on failure this check should be kept

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: Yeah. You are right. Still would prefer my suggestions. Error case above the return.

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: Yeah. But !size does check for both. 0 and false.

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: Just to be clear. If you want to have an explicit check for false `!$size` wont cut it. In that case I would suggest.

```php
if ($size === 0 || $size === false) { return false; }
return $size > self::MAX_FILE_SIZE;
```

Comment (lennartdohmann) [reply lib/Service/VerdictService.php:145]: Yes it does. !size leads to our function returns true on failure. So if the filesize can not be evaluated we won't scan it because something is corrupt because the result of filesize() is only false on failure. In that case we want to return true for "wont scan".

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: Ok, I see that. It would be a behavior change. But then I still would prefer `($size === false)` instead of `!$size` to make it more clear what's going on here.

Comment (lennartdohmann) [reply lib/Service/VerdictService.php:145]: I have no preference for the syntax, feel free to make a suggestion.

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: And it would still be a good case for a unit test. The [activity app uses phpunit](https://github.com/nextcloud/activity/tree/master/tests) as we also do in the vaas sdk.

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: > I have no preference for the syntax, feel free to make a suggestion.

its not a question of syntax is a question of explicit type check.

```php
<?php

$foobar = null;
echo var_export(!$foobar); // true
echo var_export(!$foobar === null); // false

$foobar = 0;
echo var_export(!$foobar); // true
echo var_export(!$foobar === false); // false

$foobar = false;
echo var_export(!$foobar); // true
echo var_export($foobar === false); // true
```

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: Doing this, you wouldn't even need you extra if statement because 0 is never > self::MAX_FILE_SIZE;

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: That's why explicit checks are better most of the time.

Comment (lennartdohmann) [reply lib/Service/VerdictService.php:145]: So far, we have classic PHPUnit tests outside of BATS. I would suggest to open a separate issue that implements some classic PHPUnit tests. I think your suggestion is quite good. However, I would quickly push this bugfix through for all versions because the bug was found by a stakeholder and not by us.

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: So instead of 

```php
        if ($size === 0) { return false; }
        return !$size || $size > self::MAX_FILE_SIZE;
```

Just do this
```php
        return ($size === false) || $size > self::MAX_FILE_SIZE;
```

Comment (lennartdohmann) [reply lib/Service/VerdictService.php:145]: Yes I am fine with that. Can you make this a code suggestion? I tested it and iT WoRkS LoCallY.

Comment (unglaublicherdude) [reply lib/Service/VerdictService.php:145]: You cant make code suggestions for multiple lines, so I would either do it on my local system or you do it.

**Review by unglaublicherdude — APPROVED** [review]
